= Conant Teo Jia Yu - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoURL: https://github.com/CS2103AUG2017-W14-B3/main

== Project: HitMeUp

HitMeUp is an address book application designed with the sociable user in mind. It aims to provide a one stop solution for every need: To contact, keep up
and organise.
With the cloud import feature, a user would be able to get the application
up and running a matter of minutes. Being able to group your contacts, and view each group at a glance affords
convenience like never before. Social integration to Instagram and Twitter is baked in, allowing users to view profiles
in the application itself without having to switch to a browser or check their phone.

*Code contributed*: [{repoURL}/tree/master/collated/main/conantteo.md[Functional code]] [{repoURL}/tree/master/collated/test/conantteo.md[Test code]]

=== Enhancement Added: vCard Export

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=export]

#End of Extract#

---

==== Justification

This feature is implemented to allow users to export their contacts information into a commonly used contacts file,
vCard file. vCard file is also widely used in many platforms where people can share contacts information. Users can also
decide if they want to export all contacts or only selected contacts depending on their needs. Therefore, this feature
aims to provide the convenience for users who wish to easily export their contacts from HitMeUp to another platform.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=export]

#End of Extract#

---

=== Enhancement Added: Email

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=email]

#End of Extract#

---

==== Justification

This feature is implemented to allow users to send an email to one or more persons in their list of contacts.
It allows users to customize their own message with editing tools using their own mail application. In addition, this
feature also allows user to easily attach documents to send to their contacts or save their message as a draft in their
email. Hence, this feature helps to create a channel for communication between the users and people in their list of
contacts.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=email]

#End of Extract#

---

=== Enhancement Proposed: to be updated

=== Other contributions
* Added Birthday field for a person (Pull request https://github.com/CS2103AUG2017-W14-B3/main/pull/18[#18])
* Created the GroupLabel and GroupListPanel components of the UI (Pull requests https://github.com/CS2103AUG2017-W14-B3/main/pull/87[#87])
* Modified find command to allow users to find people with the same birthday month (Pull requests https://github.com/CS2103AUG2017-W14-B3/main/pull/120[#120])
* Resolved issues when HelpWindow is opened but other actions are not working (Pull requests https://github.com/CS2103AUG2017-W14-B3/main/pull/132[#132])
