= Tan Bing Hwang - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoURL: https://github.com/CS2103AUG2017-W14-B3/main

== Project: AddressBook - Level 4
Project: HitMeUp
HitMeUp is an address book application designed with the sociable user in mind. It aims to provide a one stop solution for every need: To contact, keep up and organise. With the cloud import feature, a user would be able to get the application up and running a matter of minutes. Being able to group your contacts, and view each group at a glance affords convenience like never before. Social integration to Instagram and Twitter is baked in, allowing users to view profiles in the application itself without having to switch to a browser or check their phone.

*Code contributed*: [{repoURL}/tree/master/collated/main/tbhbhbh.md[Functional code]] [{repoURL}/tree/master/collated/test/tbhbhbh.md[Test code]]


=== Enhancement Added: Tag Delete

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tagdelete]

#End of Extract#

==== Justification

---
Being able to quickly delete tags assigned to people makes it convenient for the user to quickly organise contacts.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=tagdelete]

#End of Extract#

=== Enhancement Added: Tag Edit

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tagedit]

#End of Extract#

==== Justification

---
Being able to quickly edit tags assigned to people makes it convenient for the user to quickly organise contacts.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=tagedit]

#End of Extract#

=== Enhancement Added: Improved Find

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=find]

#End of Extract#

==== Justification

---
Allowing the user to find contacts based on a variety of possible inputs (name, tag, initial, birthday month), making
it a one-stop solution to many problems that the user might face. Very flexible since the user can do a wide search
simply with an initial or a tag, or a very specific search with a name and multiple tags together.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=find]

#End of Extract#

=== Enhancement Added: Social

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=social]

#End of Extract#

==== Justification

---
Being able to quickly view your contacts' social media is a convenient way for users to be updated on what's happening
with their contacts' lives.

==== Implementation

---

#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=social]

#End of Extract#

---
=== Other contributions

* Implemented sorting feature that is case insensitive (Pull request https://github.com/CS2103AUG2017-W14-B3/main/pull/17[#17])
* Made clicking on person cards load up social media
(Pull request https://github.com/CS2103AUG2017-W14-B3/main/pull/125[#125])

